services:
  nodejs:
    build:
      context: .
      args:
        NODE_VERSION: ${NODE_VERSION}
    container_name: nodejs
    env_file:
      - .env
    volumes:
      - ./${NAME_APP}:/app
    stdin_open: true
    tty: true
    command: ["tail", "-f", "/dev/null"]
